# Generated by Django 6.0.6 on 2026-06-24 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_identificador', models.CharField(max_length=50, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(db_index=True, max_length=15, unique=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('sospechoso', models.BooleanField(db_index=True, default=False)),
                ('fecha_alerta', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDeteccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('fecha_registro_sistema', models.DateTimeField(auto_now_add=True)),
                ('camara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detecciones', to='tracker.camara')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detecciones', to='tracker.vehiculo')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TramoCalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_calle', models.CharField(blank=True, max_length=100)),
                ('distancia', models.PositiveIntegerField(help_text='Distancia entre las dos cámaras')),
                ('velocidad_maxima', models.PositiveIntegerField(default=40, help_text='En km/h')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos_entrada', to='tracker.camara')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos_salida', to='tracker.camara')),
            ],
            options={
                'unique_together': {('origen', 'destino')},
            },
        ),
    ]
